# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :tests do
 	scan(workspace: "another-repo.xcworkspace", device: "iPhone 11", scheme: "another-repo", code_coverage: true)

 	slather(
      output_directory: "fastlane/html",
      workspace: "another-repo.xcworkspace",
      html: true,
      scheme: "another-repo",
      proj: "another-repo.xcodeproj",
      ignore: ["Pods/*"],
      verbose: true,
      show: true
  )
  end
end